grails-app/domain/com/zola/shyft/Client.groovy
package com.zola.shyft

class Client {
    String clientname
    String telephonenumber
    String contactemail
    String address
    String owner
    String contactperson
    String county
    Date dateCreated
    Date lastUpdated

    static constraints = {
        clientname nullable:false
        telephonenumber nullable:false
        contactemail nullable:false
        address nullable:false
        owner nullable:true
        contactperson nullable:false
        county nullable:false
    }
    
    String toString(){
        return "${clientname}(${county})"
    }
}

grails-app/views/admin/_menu.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#admin-menu">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                  <a class="navbar-brand" href="#">Zola Staffing System<br><span style="font-size: 10px; text-align: center;">(Administrator Dashboard)</span></a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="admin-menu">
                <nav:menu scope="admin" class="nav navbar-nav"/>
              </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
</nav>

grails-app/views/admin/clients.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page import="com.zola.shyft.Client" %>

<html>
  <head>
    <meta name="layout" content="main">
    <title>Staff</title>
    <r:require modules="bootstrap" />
  </head>
  <body class="body">
      <div class="container">
        <br>
        <br>
        <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
        </g:if>
                <div class="row">
                    <div class="col-xs-4">
                    </div>
                    <div class="col-xs-8">
                        <g:if test="${clientInstanceCount>0}">
                            <table class="table table-condensed table-striped">
                                <thead>
                                    <tr>
                                        <g:sortableColumn property="clientname" title="Client Name"/>
                                        <g:sortableColumn property="contactemail" title="Contact Email" />
                                        <g:sortableColumn property="telephonenumber" title="Phone Number"/>
                                        <th>View Client Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <g:each in="${clientInstanceList}" status="i" var="clientInstance">
                                        <tr>
                                            <td>${fieldValue(bean:clientInstance, field:"clientname")}</td>
                                            <td>${fieldValue(bean:clientInstance, field:"contactemail")}</td>
                                            <td>${fieldValue(bean:clientInstance, field:"telephonenumber")}</td>
                                            <td>
                                            <g:link action="clientdetails" id="${clientInstance.id}">Details
                                            <span class="glyphicon glyphicon-circle-arrow-right"></span></g:link>
                                                
                                            </td>
                                        </tr>
                                        </g:each>
                                </tbody>
                            </table>
                           <ul class="pagination">
                                <g:paginate total="${staffInstanceCount ?: 0}" />
                            </ul>
                            </g:if>
                        <g:else>
                            <h1>No Records Found</h1>
                            </g:else>
                    </div>
                </div>
      </div>
  </body>
</html>

grails-app/views/admin/index.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page import="com.zola.shyft.*" %>

<html>
  <head>
    <meta name="layout" content="main">
    <title>Administrator Dashboard</title>
    <gvisualization:apiImport/>
    <r:require modules="bootstrap" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'custom.styles.css')}" type="text/css">
  </head>
  <body class="body">
      <div class="container-fluid">
          <g:render template="/shared/menu" />
          <br>
          
          <g:if test="${flash.message}">
              <div class="message" role="status">${flash.message}</div>
          </g:if>
<div class="row">
          <div class="col-xs-4">
<fieldset>
    <legend class="admin-title">SHIFTS</legend>
    <div class="row-fluid" style="display: block">
        <div>
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Total for...</th>
                        <th>Shifts</th>
                        <th>Hours</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Today</td>
                        <td>${shiftstoday}</td>
                        <td>${shifthourstoday}</td>
                    </tr>
                    <tr>
                        <td>This Week</td>
                        <td>${shiftsthisweek}</td>
                        <td>${shifthoursthisweek}</td>
                    </tr>
                    <tr>
                        <td>This Month</td>
                        <td>${shiftsthismonth}</td>
                        <td>${shifthoursthismonth}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br>
        <div class="pull-right"><g:link controller="shift" action="index">View Shift Data &raquo;</g:link></div>
    </div>
    </fieldset>
        <br>
        <fieldset>
            <legend class="admin-title">STAFF</legend>
        <div class="row-fluid" style="display: block">
        <div class="admin-details">Carers:<span style="float:right">${carersnumber}</span></div>
        <div class="admin-details">Support Workers:<span style="float:right">${supportnumber}</span></div>
        <div class="admin-details">Nurses:<span style="float:right">${nursenumber}</span></div>
        <br>
        <div class="pull-right"><g:link controller="staff" action="index">View Staff Data &raquo;</g:link></div>
    </div>
        </fieldset>
        <br>
        <fieldset>
            <legend class="admin-title">CLIENTS</legend>
        <div class="row-fluid" style="display: block">
        <div class="admin-details">Total Clients Registered:<span style="float:right">${clientnumber}</span></div>
        
        <br>
        <div class="pull-right"><g:link controller="client" action="index">View Client Data &raquo;</g:link></div>
    </div>
        </fieldset>
        <br>
    </div>
    <div class="col-xs-8">

              <legend class="admin-title">TRENDS</legend>
              <div>
                      <script type="text/javascript">
                         var data = ${raw(shiftsjson)}
$(function () {
    $('#shifts-breakdown').highcharts({
        title: {
            text: 'Shifts BreakDown',
            x: -20 //center
        },
        subtitle: {
            text: 'Based on Monthly Averages (Calculated at end of Day)',
            x: -20
        },
        xAxis: {
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
        },
        yAxis: {
            title: {
                text: 'Number of Shifts'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: ''
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Shifts',
            data: ${shiftsstring}
        }]
    });
});
		</script>
                 <g:javascript src="highcharts.js"></g:javascript>
    <g:javascript src="modules/exporting.js"></g:javascript>
    <div class="row-fluid" id="shifts-breakdown"></div>
    <div></div>
              </div>
              
          </div>
</div>
      </div>
  </body>
</html>

grails-app/views/admin/staff.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page import="com.zola.shyft.Staff" %>

<html>
  <head>
    <meta name="layout" content="main">
    <title>Staff</title>
    <r:require modules="bootstrap" />
  </head>
  <body class="body">
      <div class="container">
        <br>
        <br>
        <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
        </g:if>
                <div class="row">
                    <div class="col-xs-5">
                    </div>
                    <div class="col-xs-7">
                        <g:if test="${staffInstanceCount>0}">
                            <table class="table table-condensed table-striped">
                                <thead>
                                    <tr>
                                        <g:sortableColumn property="candidatename" title="Employee Name"/>
                                        <g:sortableColumn property="email" title="Enail" />
                                        <g:sortableColumn property="contactnumber" title="Phone Number"/>
                                        <th>View Staff Details</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <g:each in="${staffInstanceList}" status="i" var="staffInstance">
                                        <tr>
                                            <td>${fieldValue(bean:staffInstance, field:"candidatename")}</td>
                                            <td>${fieldValue(bean:staffInstance, field:"email")}</td>
                                            <td>${fieldValue(bean:staffInstance, field:"contactnumber")}</td>
                                            <td><g:link action="staffdetails" id="${staffInstance.id}">Details
                                            <span class="glyphicon glyphicon-circle-arrow-right"></span></g:link>
                                            </td>
                                        </tr>
                                        </g:each>
                                </tbody>
                            </table>
                           <div class="pagination">
                                <g:paginate total="${staffInstanceCount ?: 0}" />
                            </div>
                            </g:if>
                        <g:else>
                            <h1>No Records Found</h1>
                            </g:else>
                    </div>
                </div>
      </div>
  </body>
</html>

grails-app/views/admin/staffdetails.gsp
<!--
  To change this license header, choose License Headers in Project Properties.
  To change this template file, choose Tools | Templates
  and open the template in the editor.
-->

<%@ page contentType="text/html;charset=UTF-8" %>

<html>
  <head>
    <meta name="layout" content="main">
    <title>Staff Details</title>
    <r:require modules="bootstrap" />
  </head>
  <body class="body">
      <div class="container">
        <br>
        <br>
        <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
        </g:if>
            <div class="row">
                <div class="col-xs-3">
                    <g:render template="/shared/adminsecondarymenu"/>
                </div>
                <div class="col-xs-9">
                    <fieldset>
                        <legend>Staff Details</legend>
                    </fieldset>
                </div>
            </div>
      </div>
  </body>
</html>