grails-app/domain/com/zola/shyft/MandatoryTraining.groovy
package com.zola.shyft

import org.joda.time.LocalDate

class MandatoryTraining {
    String training
    Boolean undertaken
    Date dateCreated
    Date lastUpdated
    LocalDate datecompleted
    LocalDate expirydate
    
    static belongsTo= [staff:Staff]

    static constraints = {
        training nullbale:false, blank:false
        undertaken nullable:false, blank:false
        datecompleted nullable:true, blank:true
        expirydate nullable:true, blank:false
    }
    
    String toString(){
        return "${training}"
    }
}

grails-app/controllers/com/zola/shyft/MandatoryTrainingController.groovy
package com.zola.shyft



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class MandatoryTrainingController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond MandatoryTraining.list(params), model:[mandatoryTrainingInstanceCount: MandatoryTraining.count()]
    }

    def show(MandatoryTraining mandatoryTrainingInstance) {
        respond mandatoryTrainingInstance
    }

    def create() {
        respond new MandatoryTraining(params)
    }

    @Transactional
    def save(MandatoryTraining mandatoryTrainingInstance) {
        if (mandatoryTrainingInstance == null) {
            notFound()
            return
        }

        if (mandatoryTrainingInstance.hasErrors()) {
            respond mandatoryTrainingInstance.errors, view:'create'
            return
        }

        mandatoryTrainingInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'mandatoryTraining.label', default: 'MandatoryTraining'), mandatoryTrainingInstance.id])
                redirect mandatoryTrainingInstance.staff
            }
            '*' { respond mandatoryTrainingInstance, [status: CREATED] }
        }
    }

    def edit(MandatoryTraining mandatoryTrainingInstance) {
        respond mandatoryTrainingInstance
    }

    @Transactional
    def update(MandatoryTraining mandatoryTrainingInstance) {
        if (mandatoryTrainingInstance == null) {
            notFound()
            return
        }

        if (mandatoryTrainingInstance.hasErrors()) {
            respond mandatoryTrainingInstance.errors, view:'edit'
            return
        }

        mandatoryTrainingInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'MandatoryTraining.label', default: 'MandatoryTraining'), mandatoryTrainingInstance.id])
                redirect mandatoryTrainingInstance
            }
            '*'{ respond mandatoryTrainingInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(MandatoryTraining mandatoryTrainingInstance) {

        if (mandatoryTrainingInstance == null) {
            notFound()
            return
        }

        mandatoryTrainingInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'MandatoryTraining.label', default: 'MandatoryTraining'), mandatoryTrainingInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'mandatoryTraining.label', default: 'MandatoryTraining'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/mandatoryTraining/_form.gsp
<%@ page import="com.zola.shyft.MandatoryTraining" %>



<div class="fieldcontain ${hasErrors(bean: mandatoryTrainingInstance, field: 'training', 'error')} required">
	<label for="training">
		<g:message code="mandatoryTraining.training.label" default="Training" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="training" required="" value="${mandatoryTrainingInstance?.training}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: mandatoryTrainingInstance, field: 'undertaken', 'error')} ">
	<label for="undertaken">
		<g:message code="mandatoryTraining.undertaken.label" default="Undertaken" />
		
	</label>
	<g:checkBox name="undertaken" value="${mandatoryTrainingInstance?.undertaken}" />

</div>

<div class="fieldcontain ${hasErrors(bean: mandatoryTrainingInstance, field: 'datecompleted', 'error')} ">
	<label for="datecompleted">
		<g:message code="mandatoryTraining.datecompleted.label" default="Datecompleted" />
		
	</label>
	<joda:dateField name="datecompleted" value="${mandatoryTrainingInstance?.datecompleted}" />

</div>

<div class="fieldcontain ${hasErrors(bean: mandatoryTrainingInstance, field: 'expirydate', 'error')} ">
	<label for="expirydate">
		<g:message code="mandatoryTraining.expirydate.label" default="Expirydate" />
		
	</label>
	<joda:dateField name="expirydate" value="${mandatoryTrainingInstance?.expirydate}" />

</div>

<div class="fieldcontain ${hasErrors(bean: mandatoryTrainingInstance, field: 'staff', 'error')} required">
	<label for="staff">
		<g:message code="mandatoryTraining.staff.label" default="Staff" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="staff" name="staff.id" from="${com.zola.shyft.Staff.list()}" optionKey="id" required="" value="${mandatoryTrainingInstance?.staff?.id}" class="many-to-one"/>

</div>

grails-app/views/mandatoryTraining/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mandatoryTraining.label', default: 'MandatoryTraining')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-mandatoryTraining" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-mandatoryTraining" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${mandatoryTrainingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${mandatoryTrainingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:mandatoryTrainingInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/mandatoryTraining/edit.gsp
<%@ page import="com.zola.shyft.MandatoryTraining" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mandatoryTraining.label', default: 'MandatoryTraining')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-mandatoryTraining" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-mandatoryTraining" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${mandatoryTrainingInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${mandatoryTrainingInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:mandatoryTrainingInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${mandatoryTrainingInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/mandatoryTraining/index.gsp
<%@ page import="com.zola.shyft.MandatoryTraining" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mandatoryTraining.label', default: 'MandatoryTraining')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-mandatoryTraining" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-mandatoryTraining" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="training" title="${message(code: 'mandatoryTraining.training.label', default: 'Training')}" />
					
						<g:sortableColumn property="undertaken" title="${message(code: 'mandatoryTraining.undertaken.label', default: 'Undertaken')}" />
					
						<g:sortableColumn property="datecompleted" title="${message(code: 'mandatoryTraining.datecompleted.label', default: 'Datecompleted')}" />
					
						<g:sortableColumn property="expirydate" title="${message(code: 'mandatoryTraining.expirydate.label', default: 'Expirydate')}" />
					
						<th><g:message code="mandatoryTraining.staff.label" default="Staff" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${mandatoryTrainingInstanceList}" status="i" var="mandatoryTrainingInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${mandatoryTrainingInstance.id}">${fieldValue(bean: mandatoryTrainingInstance, field: "training")}</g:link></td>
					
						<td><g:formatBoolean boolean="${mandatoryTrainingInstance.undertaken}" /></td>
					
						<td>${fieldValue(bean: mandatoryTrainingInstance, field: "datecompleted")}</td>
					
						<td>${fieldValue(bean: mandatoryTrainingInstance, field: "expirydate")}</td>
					
						<td>${fieldValue(bean: mandatoryTrainingInstance, field: "staff")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${mandatoryTrainingInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/mandatoryTraining/show.gsp
<%@ page import="com.zola.shyft.MandatoryTraining" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'mandatoryTraining.label', default: 'MandatoryTraining')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-mandatoryTraining" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-mandatoryTraining" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list mandatoryTraining">
			
				<g:if test="${mandatoryTrainingInstance?.training}">
				<li class="fieldcontain">
					<span id="training-label" class="property-label"><g:message code="mandatoryTraining.training.label" default="Training" /></span>
					
						<span class="property-value" aria-labelledby="training-label"><g:fieldValue bean="${mandatoryTrainingInstance}" field="training"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${mandatoryTrainingInstance?.undertaken}">
				<li class="fieldcontain">
					<span id="undertaken-label" class="property-label"><g:message code="mandatoryTraining.undertaken.label" default="Undertaken" /></span>
					
						<span class="property-value" aria-labelledby="undertaken-label"><g:formatBoolean boolean="${mandatoryTrainingInstance?.undertaken}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${mandatoryTrainingInstance?.datecompleted}">
				<li class="fieldcontain">
					<span id="datecompleted-label" class="property-label"><g:message code="mandatoryTraining.datecompleted.label" default="Datecompleted" /></span>
					
						<span class="property-value" aria-labelledby="datecompleted-label"><g:fieldValue bean="${mandatoryTrainingInstance}" field="datecompleted"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${mandatoryTrainingInstance?.expirydate}">
				<li class="fieldcontain">
					<span id="expirydate-label" class="property-label"><g:message code="mandatoryTraining.expirydate.label" default="Expirydate" /></span>
					
						<span class="property-value" aria-labelledby="expirydate-label"><g:fieldValue bean="${mandatoryTrainingInstance}" field="expirydate"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${mandatoryTrainingInstance?.staff}">
				<li class="fieldcontain">
					<span id="staff-label" class="property-label"><g:message code="mandatoryTraining.staff.label" default="Staff" /></span>
					
						<span class="property-value" aria-labelledby="staff-label"><g:link controller="staff" action="show" id="${mandatoryTrainingInstance?.staff?.id}">${mandatoryTrainingInstance?.staff?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:mandatoryTrainingInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${mandatoryTrainingInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>